<a href="https://colab.research.google.com/github/Pranayshukla0610/Data-Science-Projects/blob/main/Notebook_2_Product_Data_Generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import random

In [3]:
random.seed(42)
np.random.seed(42)

In [4]:
NUMBER_OF_PRODUCTS = 500

In [5]:
categories = {

    "Electronics":[
        "Laptop",
        "Desktop",
        "Smartphone",
        "Tablet",
        "Smartwatch",
        "Printer",
        "Monitor",
        "Keyboard",
        "Mouse",
        "Headphones"
    ],

    "Furniture":[
        "Office Chair",
        "Dining Table",
        "Sofa",
        "Bookshelf",
        "Wardrobe",
        "Coffee Table",
        "Bed",
        "TV Unit"
    ],

    "Office Supplies":[
        "Notebook",
        "Pen",
        "Marker",
        "Stapler",
        "Calculator",
        "Paper Ream",
        "File Folder",
        "Whiteboard"
    ],

    "Kitchen":[
        "Mixer Grinder",
        "Pressure Cooker",
        "Cookware Set",
        "Knife Set",
        "Microwave",
        "Gas Stove",
        "Water Bottle",
        "Storage Container"
    ],

    "Home Appliances":[
        "Refrigerator",
        "Washing Machine",
        "Air Conditioner",
        "Vacuum Cleaner",
        "Ceiling Fan",
        "Air Purifier"
    ],

    "Clothing":[
        "T-Shirt",
        "Jeans",
        "Shirt",
        "Jacket",
        "Kurta",
        "Hoodie"
    ],

    "Footwear":[
        "Running Shoes",
        "Formal Shoes",
        "Sandals",
        "Sneakers",
        "Slippers"
    ],

    "Beauty":[
        "Face Wash",
        "Shampoo",
        "Conditioner",
        "Lipstick",
        "Perfume",
        "Moisturizer"
    ],

    "Grocery":[
        "Rice",
        "Wheat Flour",
        "Cooking Oil",
        "Sugar",
        "Tea",
        "Coffee"
    ],

    "Books":[
        "Novel",
        "Biography",
        "Textbook",
        "Comics",
        "Dictionary"
    ],

    "Sports":[
        "Cricket Bat",
        "Football",
        "Badminton Racket",
        "Tennis Ball",
        "Yoga Mat"
    ],

    "Toys":[
        "Puzzle",
        "Building Blocks",
        "Remote Car",
        "Doll",
        "Board Game"
    ],

    "Automotive":[
        "Car Cover",
        "Engine Oil",
        "Helmet",
        "Car Vacuum",
        "Seat Cover"
    ],

    "Pet Supplies":[
        "Dog Food",
        "Cat Food",
        "Pet Shampoo",
        "Pet Toy",
        "Pet Bed"
    ],

    "Healthcare":[
        "Thermometer",
        "Blood Pressure Monitor",
        "First Aid Kit",
        "Vitamin Tablets",
        "Face Mask"
    ]

}

In [6]:
brands = {

    "Electronics":[
        "Dell",
        "HP",
        "Lenovo",
        "Apple",
        "Samsung",
        "Asus",
        "Acer",
        "LG",
        "Sony",
        "Logitech"
    ],

    "Furniture":[
        "Godrej",
        "Nilkamal",
        "IKEA",
        "Urban Ladder",
        "Home Centre"
    ],

    "Office Supplies":[
        "Classmate",
        "Cello",
        "Camlin",
        "Faber-Castell",
        "Kangaro"
    ],

    "Kitchen":[
        "Prestige",
        "Butterfly",
        "Pigeon",
        "Milton",
        "Borosil"
    ],

    "Home Appliances":[
        "LG",
        "Whirlpool",
        "Samsung",
        "Bosch",
        "IFB"
    ],

    "Clothing":[
        "Levis",
        "Allen Solly",
        "Van Heusen",
        "US Polo",
        "Nike"
    ],

    "Footwear":[
        "Nike",
        "Adidas",
        "Puma",
        "Bata",
        "Woodland"
    ],

    "Beauty":[
        "Lakme",
        "Nivea",
        "Mamaearth",
        "L'Oreal",
        "Himalaya"
    ],

    "Grocery":[
        "Fortune",
        "Aashirvaad",
        "Tata",
        "MDH",
        "Patanjali"
    ],

    "Books":[
        "Penguin",
        "HarperCollins",
        "Oxford",
        "McGraw Hill",
        "Pearson"
    ],

    "Sports":[
        "SG",
        "MRF",
        "Yonex",
        "Nike",
        "Adidas"
    ],

    "Toys":[
        "Lego",
        "Funskool",
        "Hasbro",
        "Barbie",
        "Hot Wheels"
    ],

    "Automotive":[
        "Bosch",
        "Castrol",
        "3M",
        "Shell",
        "Steelbird"
    ],

    "Pet Supplies":[
        "Pedigree",
        "Whiskas",
        "Drools",
        "Royal Canin",
        "Himalaya"
    ],

    "Healthcare":[
        "Omron",
        "Dr Morepen",
        "Accu-Chek",
        "Dettol",
        "Himalaya"
    ]

}

In [7]:
suppliers = [

    "ABC Traders",
    "Prime Distributors",
    "National Wholesale",
    "Elite Suppliers",
    "Retail Connect",
    "Sunrise Enterprises",
    "Global Imports",
    "Shree Distributors",
    "Om Trading Company",
    "Metro Suppliers",

    "Eastern Supply Chain",
    "Western Traders",
    "North India Wholesale",
    "South India Distribution",
    "Universal Retail Supply",

    "Apex Trading",
    "Infinity Distributors",
    "Blue Sky Suppliers",
    "Vertex Supply",
    "Smart Retail Hub",

    "Future Distributors",
    "Golden Enterprises",
    "Quick Supply Chain",
    "Trusted Wholesalers",
    "NextGen Distributors"

]

In [8]:
pricing_rules = {

    "Electronics": (5000, 80000),

    "Furniture": (2000, 50000),

    "Office Supplies": (20, 2000),

    "Kitchen": (200, 20000),

    "Home Appliances": (3000, 120000),

    "Clothing": (300, 6000),

    "Footwear": (400, 12000),

    "Beauty": (100, 3000),

    "Grocery": (50, 2000),

    "Books": (150, 3000),

    "Sports": (300, 25000),

    "Toys": (200, 8000),

    "Automotive": (300, 30000),

    "Pet Supplies": (200, 5000),

    "Healthcare": (100, 15000)

}

In [9]:
stock_rules = {

    "Electronics": (10, 80),

    "Furniture": (5, 40),

    "Office Supplies": (100, 1000),

    "Kitchen": (30, 300),

    "Home Appliances": (10, 60),

    "Clothing": (50, 500),

    "Footwear": (40, 400),

    "Beauty": (100, 800),

    "Grocery": (200, 1500),

    "Books": (50, 500),

    "Sports": (20, 200),

    "Toys": (30, 300),

    "Automotive": (20, 150),

    "Pet Supplies": (20, 200),

    "Healthcare": (50, 500)

}

In [10]:
product_ids = [
    f"P{str(i).zfill(5)}"
    for i in range(1, NUMBER_OF_PRODUCTS + 1)
]

print(product_ids[:10])

['P00001', 'P00002', 'P00003', 'P00004', 'P00005', 'P00006', 'P00007', 'P00008', 'P00009', 'P00010']

In [11]:
print("=" * 60)

print("PRODUCT DATA GENERATION CONFIGURATION")

print("=" * 60)

print("Total Products :", NUMBER_OF_PRODUCTS)

print("Categories :", len(categories))

print("Suppliers :", len(suppliers))

print("Unique Product IDs :", len(set(product_ids)))

print("=" * 60)

============================================================
PRODUCT DATA GENERATION CONFIGURATION
============================================================
Total Products : 500
Categories : 15
Suppliers : 25
Unique Product IDs : 500
============================================================

In [12]:
product_name_list = []
brand_list = []
category_list = []
sub_category_list = []
supplier_list = []
cost_price_list = []
selling_price_list = []
profit_margin_list = []
stock_quantity_list = []

In [13]:
for product_id in product_ids:

    # Select Category
    category = random.choice(list(categories.keys()))

    # Select Sub Category
    sub_category = random.choice(categories[category])

    # Select Brand
    brand = random.choice(brands[category])

    # Supplier
    supplier = random.choice(suppliers)

    # Cost Price
    min_price, max_price = pricing_rules[category]

    cost_price = round(
        random.uniform(min_price, max_price),
        2
    )

    # Selling Price
    markup = random.uniform(1.10, 1.40)

    selling_price = round(
        cost_price * markup,
        2
    )

    # Profit Margin
    profit_margin = round(
        selling_price - cost_price,
        2
    )

    # Stock Quantity
    min_stock, max_stock = stock_rules[category]

    stock_quantity = random.randint(
        min_stock,
        max_stock
    )

    # Product Name
    product_name = f"{brand} {sub_category}"

    # Store Values
    product_name_list.append(product_name)
    brand_list.append(brand)
    category_list.append(category)
    sub_category_list.append(sub_category)
    supplier_list.append(supplier)
    cost_price_list.append(cost_price)
    selling_price_list.append(selling_price)
    profit_margin_list.append(profit_margin)
    stock_quantity_list.append(stock_quantity)

In [14]:
products_df = pd.DataFrame({

    "product_id": product_ids,

    "product_name": product_name_list,

    "brand": brand_list,

    "category": category_list,

    "sub_category": sub_category_list,

    "supplier": supplier_list,

    "cost_price": cost_price_list,

    "selling_price": selling_price_list,

    "profit_margin": profit_margin_list,

    "stock_quantity": stock_quantity_list

})

In [15]:
products_df.head()

,product_id,product_name,brand,category,sub_category,supplier,cost_price,selling_price,profit_margin,stock_quantity
0,P00001,SG Cricket Bat,SG,Sports,Cricket Bat,Trusted Wholesalers,7093.22,8277.53,1184.31,46
1,P00002,SG Yoga Mat,SG,Sports,Yoga Mat,Vertex Supply,10721.47,11889.46,1167.99,75
2,P00003,Borosil Mixer Grinder,Borosil,Kitchen,Mixer Grinder,Global Imports,14377.19,18839.83,4462.64,244
3,P00004,Borosil Storage Container,Borosil,Kitchen,Storage Container,Om Trading Company,16226.72,17881.03,1654.31,111
4,P00005,Hasbro Doll,Hasbro,Toys,Doll,Om Trading Company,1412.74,1959.70,546.96,202

In [16]:
products_df.tail()

,product_id,product_name,brand,category,sub_category,supplier,cost_price,selling_price,profit_margin,stock_quantity
495,P00496,Funskool Board Game,Funskool,Toys,Board Game,Universal Retail Supply,3072.53,4275.60,1203.07,130
496,P00497,Funskool Board Game,Funskool,Toys,Board Game,Retail Connect,249.75,305.45,55.70,149
497,P00498,Fortune Cooking Oil,Fortune,Grocery,Cooking Oil,Eastern Supply Chain,52.85,68.56,15.71,829
498,P00499,Home Centre Bookshelf,Home Centre,Furniture,Bookshelf,Shree Distributors,22151.16,30753.69,8602.53,14
499,P00500,Lego Remote Car,Lego,Toys,Remote Car,Prime Distributors,7385.94,10112.73,2726.79,296

In [18]:
products_df.shape

(500, 10)

In [19]:
products_df.columns

Index(['product_id', 'product_name', 'brand', 'category', 'sub_category',
       'supplier', 'cost_price', 'selling_price', 'profit_margin',
       'stock_quantity'],
      dtype='object')

In [20]:
products_df.dtypes

product_id         object
product_name       object
brand              object
category           object
sub_category       object
supplier           object
cost_price        float64
selling_price     float64
profit_margin     float64
stock_quantity      int64
dtype: object

In [21]:
products_df.sample(10)

,product_id,product_name,brand,category,sub_category,supplier,cost_price,selling_price,profit_margin,stock_quantity
361,P00362,Adidas Tennis Ball,Adidas,Sports,Tennis Ball,Apex Trading,1458.04,1754.50,296.46,184
73,P00074,Drools Cat Food,Drools,Pet Supplies,Cat Food,Shree Distributors,4071.50,4658.64,587.14,31
374,P00375,Lego Building Blocks,Lego,Toys,Building Blocks,Om Trading Company,4515.83,5758.63,1242.80,243
155,P00156,Van Heusen T-Shirt,Van Heusen,Clothing,T-Shirt,Western Traders,2436.59,2786.66,350.07,321
104,P00105,McGraw Hill Dictionary,McGraw Hill,Books,Dictionary,Eastern Supply Chain,231.79,314.14,82.35,143
394,P00395,Puma Slippers,Puma,Footwear,Slippers,North India Wholesale,9165.07,10466.37,1301.30,392
377,P00378,Barbie Doll,Barbie,Toys,Doll,Sunrise Enterprises,5915.62,7132.18,1216.56,101
124,P00125,Lego Doll,Lego,Toys,Doll,Golden Enterprises,2020.71,2383.16,362.45,131
68,P00069,Hot Wheels Remote Car,Hot Wheels,Toys,Remote Car,Retail Connect,1696.35,2204.37,508.02,224
450,P00451,Whiskas Cat Food,Whiskas,Pet Supplies,Cat Food,Shree Distributors,901.97,1079.32,177.35,83

In [22]:
products_df["category"].value_counts()

category
Toys               44
Beauty             44
Grocery            43
Clothing           42
Pet Supplies       36
Footwear           35
Kitchen            34
Automotive         34
Sports             31
Books              28
Furniture          28
Home Appliances    27
Electronics        27
Healthcare         26
Office Supplies    21
Name: count, dtype: int64

In [23]:
products_df["brand"].value_counts().head(15)

brand
Himalaya      19
Nike          18
Mamaearth     15
Hot Wheels    13
Bosch         13
Adidas        12
Barbie        12
Patanjali     10
Steelbird     10
L'Oreal       10
Van Heusen    10
US Polo       10
Whiskas       10
Tata           9
Fortune        9
Name: count, dtype: int64

In [24]:
products_df["cost_price"].describe()

count       500.000000
mean      11632.322980
std       19242.110739
min          52.850000
25%        1492.940000
50%        4095.935000
75%       12994.847500
max      116012.220000
Name: cost_price, dtype: float64

In [25]:
products_df["selling_price"].describe()

count       500.000000
mean      14480.380700
std       23921.434299
min          68.560000
25%        1867.215000
50%        5000.975000
75%       16277.972500
max      144949.300000
Name: selling_price, dtype: float64

In [26]:
products_df["stock_quantity"].describe()

count     500.000000
mean      265.188000
std       277.967481
min         5.000000
25%        67.000000
50%       180.000000
75%       351.500000
max      1485.000000
Name: stock_quantity, dtype: float64

In [27]:
products_df.sort_values(
    by="selling_price"
).head(10)

,product_id,product_name,brand,category,sub_category,supplier,cost_price,selling_price,profit_margin,stock_quantity
497,P00498,Fortune Cooking Oil,Fortune,Grocery,Cooking Oil,Eastern Supply Chain,52.85,68.56,15.71,829
379,P00380,Fortune Rice,Fortune,Grocery,Rice,Golden Enterprises,144.60,159.34,14.74,481
16,P00017,Fortune Sugar,Fortune,Grocery,Sugar,NextGen Distributors,141.88,160.74,18.86,1485
442,P00443,Patanjali Cooking Oil,Patanjali,Grocery,Cooking Oil,NextGen Distributors,131.14,172.54,41.40,1318
122,P00123,Cello Stapler,Cello,Office Supplies,Stapler,Blue Sky Suppliers,168.63,185.63,17.00,561
254,P00255,Kangaro Pen,Kangaro,Office Supplies,Pen,Western Traders,154.01,193.72,39.71,619
346,P00347,MDH Sugar,MDH,Grocery,Sugar,Vertex Supply,162.59,201.40,38.81,831
433,P00434,Kangaro Calculator,Kangaro,Office Supplies,Calculator,Vertex Supply,187.81,214.14,26.33,220
118,P00119,Kangaro Marker,Kangaro,Office Supplies,Marker,Metro Suppliers,188.66,221.57,32.91,671
128,P00129,MDH Tea,MDH,Grocery,Tea,Universal Retail Supply,206.86,230.02,23.16,1084

In [28]:
products_df.sort_values(
    by="stock_quantity",
    ascending=False
).head(10)

,product_id,product_name,brand,category,sub_category,supplier,cost_price,selling_price,profit_margin,stock_quantity
16,P00017,Fortune Sugar,Fortune,Grocery,Sugar,NextGen Distributors,141.88,160.74,18.86,1485
171,P00172,MDH Rice,MDH,Grocery,Rice,Western Traders,1362.02,1772.94,410.92,1397
402,P00403,Patanjali Tea,Patanjali,Grocery,Tea,South India Distribution,251.42,283.32,31.90,1335
442,P00443,Patanjali Cooking Oil,Patanjali,Grocery,Cooking Oil,NextGen Distributors,131.14,172.54,41.40,1318
315,P00316,Tata Sugar,Tata,Grocery,Sugar,Sunrise Enterprises,946.34,1192.33,245.99,1318
18,P00019,Patanjali Cooking Oil,Patanjali,Grocery,Cooking Oil,ABC Traders,1376.55,1561.51,184.96,1299
234,P00235,Tata Sugar,Tata,Grocery,Sugar,Retail Connect,1356.73,1829.81,473.08,1278
317,P00318,Aashirvaad Cooking Oil,Aashirvaad,Grocery,Cooking Oil,Metro Suppliers,1553.79,2037.75,483.96,1201
106,P00107,Patanjali Rice,Patanjali,Grocery,Rice,Global Imports,216.95,285.51,68.56,1200
453,P00454,Tata Coffee,Tata,Grocery,Coffee,Quick Supply Chain,1875.86,2271.14,395.28,1199

In [29]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      500 non-null    object
 1   product_name    500 non-null    object
 2   brand           500 non-null    object
 3   category        500 non-null    object
 4   sub_category    500 non-null    object
 5   supplier        500 non-null    object
 6   cost_price      500 non-null    float64
 7   selling_price   500 non-null    float64
 8   profit_margin   500 non-null    float64
 9   stock_quantity  500 non-null    int64
dtypes: float64(3), int64(1), object(6)
memory usage: 39.2+ KB

In [30]:
products_df.head()

,product_id,product_name,brand,category,sub_category,supplier,cost_price,selling_price,profit_margin,stock_quantity
0,P00001,SG Cricket Bat,SG,Sports,Cricket Bat,Trusted Wholesalers,7093.22,8277.53,1184.31,46
1,P00002,SG Yoga Mat,SG,Sports,Yoga Mat,Vertex Supply,10721.47,11889.46,1167.99,75
2,P00003,Borosil Mixer Grinder,Borosil,Kitchen,Mixer Grinder,Global Imports,14377.19,18839.83,4462.64,244
3,P00004,Borosil Storage Container,Borosil,Kitchen,Storage Container,Om Trading Company,16226.72,17881.03,1654.31,111
4,P00005,Hasbro Doll,Hasbro,Toys,Doll,Om Trading Company,1412.74,1959.70,546.96,202

In [31]:
products_df.isnull().sum()

product_id        0
product_name      0
brand             0
category          0
sub_category      0
supplier          0
cost_price        0
selling_price     0
profit_margin     0
stock_quantity    0
dtype: int64

In [32]:
products_df.isnull().sum()

product_id        0
product_name      0
brand             0
category          0
sub_category      0
supplier          0
cost_price        0
selling_price     0
profit_margin     0
stock_quantity    0
dtype: int64

In [33]:
products_df["product_name"].duplicated().sum()

np.int64(200)

In [34]:
(products_df["selling_price"] <= products_df["cost_price"]).sum()

np.int64(0)

In [35]:
(products_df["stock_quantity"] <= 0).sum()

np.int64(0)

In [36]:
products_df[
    [
        "cost_price",
        "selling_price",
        "profit_margin"
    ]
].describe()

          cost_price  selling_price  profit_margin
count     500.000000     500.000000     500.000000
mean    11632.322980   14480.380700    2848.057720
std     19242.110739   23921.434299    4952.108035
min        52.850000      68.560000      14.740000
25%      1492.940000    1867.215000     342.795000
50%      4095.935000    5000.975000     972.325000
75%     12994.847500   16277.972500    3241.540000
max    116012.220000  144949.300000   31942.860000

In [37]:
products_df[
    [
        "cost_price",
        "selling_price",
        "profit_margin"
    ]
].describe()

          cost_price  selling_price  profit_margin
count     500.000000     500.000000     500.000000
mean    11632.322980   14480.380700    2848.057720
std     19242.110739   23921.434299    4952.108035
min        52.850000      68.560000      14.740000
25%      1492.940000    1867.215000     342.795000
50%      4095.935000    5000.975000     972.325000
75%     12994.847500   16277.972500    3241.540000
max    116012.220000  144949.300000   31942.860000

In [38]:
products_df["brand"].value_counts()

brand
Himalaya      19
Nike          18
Mamaearth     15
Hot Wheels    13
Bosch         13
              ..
Sony           2
Acer           2
Apple          2
Lenovo         1
Oxford         1
Name: count, Length: 72, dtype: int64

In [39]:
products_df.sort_values(
    by="profit_margin",
    ascending=False
).head(10)

,product_id,product_name,brand,category,sub_category,supplier,cost_price,selling_price,profit_margin,stock_quantity
250,P00251,Whirlpool Washing Machine,Whirlpool,Home Appliances,Washing Machine,Blue Sky Suppliers,113006.44,144949.30,31942.86,37
333,P00334,Whirlpool Air Purifier,Whirlpool,Home Appliances,Air Purifier,ABC Traders,89184.29,119259.93,30075.64,46
233,P00234,Bosch Air Purifier,Bosch,Home Appliances,Air Purifier,Retail Connect,72619.82,100317.07,27697.25,29
355,P00356,Logitech Monitor,Logitech,Electronics,Monitor,NextGen Distributors,75217.84,102801.15,27583.31,40
70,P00071,Whirlpool Air Conditioner,Whirlpool,Home Appliances,Air Conditioner,South India Distribution,94933.78,121704.96,26771.18,30
459,P00460,Apple Monitor,Apple,Electronics,Monitor,Quick Supply Chain,73205.54,99899.53,26693.99,48
35,P00036,Dell Mouse,Dell,Electronics,Mouse,National Wholesale,74477.52,100887.90,26410.38,31
307,P00308,Samsung Ceiling Fan,Samsung,Home Appliances,Ceiling Fan,Infinity Distributors,99909.86,125856.65,25946.79,55
319,P00320,IFB Refrigerator,IFB,Home Appliances,Refrigerator,Golden Enterprises,66553.33,91093.42,24540.09,35
47,P00048,Bosch Washing Machine,Bosch,Home Appliances,Washing Machine,Blue Sky Suppliers,85314.17,109501.02,24186.85,51

In [40]:
products_df.sort_values(
    by="profit_margin",
    ascending=False
).head(10)

,product_id,product_name,brand,category,sub_category,supplier,cost_price,selling_price,profit_margin,stock_quantity
250,P00251,Whirlpool Washing Machine,Whirlpool,Home Appliances,Washing Machine,Blue Sky Suppliers,113006.44,144949.30,31942.86,37
333,P00334,Whirlpool Air Purifier,Whirlpool,Home Appliances,Air Purifier,ABC Traders,89184.29,119259.93,30075.64,46
233,P00234,Bosch Air Purifier,Bosch,Home Appliances,Air Purifier,Retail Connect,72619.82,100317.07,27697.25,29
355,P00356,Logitech Monitor,Logitech,Electronics,Monitor,NextGen Distributors,75217.84,102801.15,27583.31,40
70,P00071,Whirlpool Air Conditioner,Whirlpool,Home Appliances,Air Conditioner,South India Distribution,94933.78,121704.96,26771.18,30
459,P00460,Apple Monitor,Apple,Electronics,Monitor,Quick Supply Chain,73205.54,99899.53,26693.99,48
35,P00036,Dell Mouse,Dell,Electronics,Mouse,National Wholesale,74477.52,100887.90,26410.38,31
307,P00308,Samsung Ceiling Fan,Samsung,Home Appliances,Ceiling Fan,Infinity Distributors,99909.86,125856.65,25946.79,55
319,P00320,IFB Refrigerator,IFB,Home Appliances,Refrigerator,Golden Enterprises,66553.33,91093.42,24540.09,35
47,P00048,Bosch Washing Machine,Bosch,Home Appliances,Washing Machine,Blue Sky Suppliers,85314.17,109501.02,24186.85,51

In [41]:
products_df.sort_values(
    by="selling_price",
    ascending=False
).head(10)

,product_id,product_name,brand,category,sub_category,supplier,cost_price,selling_price,profit_margin,stock_quantity
250,P00251,Whirlpool Washing Machine,Whirlpool,Home Appliances,Washing Machine,Blue Sky Suppliers,113006.44,144949.30,31942.86,37
431,P00432,Bosch Air Purifier,Bosch,Home Appliances,Air Purifier,Infinity Distributors,116012.22,138521.05,22508.83,34
481,P00482,Bosch Air Purifier,Bosch,Home Appliances,Air Purifier,Trusted Wholesalers,114551.07,134207.03,19655.96,25
260,P00261,LG Washing Machine,LG,Home Appliances,Washing Machine,Global Imports,106637.48,127397.53,20760.05,29
307,P00308,Samsung Ceiling Fan,Samsung,Home Appliances,Ceiling Fan,Infinity Distributors,99909.86,125856.65,25946.79,55
70,P00071,Whirlpool Air Conditioner,Whirlpool,Home Appliances,Air Conditioner,South India Distribution,94933.78,121704.96,26771.18,30
333,P00334,Whirlpool Air Purifier,Whirlpool,Home Appliances,Air Purifier,ABC Traders,89184.29,119259.93,30075.64,46
406,P00407,Samsung Vacuum Cleaner,Samsung,Home Appliances,Vacuum Cleaner,Apex Trading,94572.00,114274.89,19702.89,25
273,P00274,LG Washing Machine,LG,Home Appliances,Washing Machine,ABC Traders,89073.96,111316.90,22242.94,34
47,P00048,Bosch Washing Machine,Bosch,Home Appliances,Washing Machine,Blue Sky Suppliers,85314.17,109501.02,24186.85,51

In [42]:
products_df.sort_values(
    by="stock_quantity",
    ascending=False
).head(10)

,product_id,product_name,brand,category,sub_category,supplier,cost_price,selling_price,profit_margin,stock_quantity
16,P00017,Fortune Sugar,Fortune,Grocery,Sugar,NextGen Distributors,141.88,160.74,18.86,1485
171,P00172,MDH Rice,MDH,Grocery,Rice,Western Traders,1362.02,1772.94,410.92,1397
402,P00403,Patanjali Tea,Patanjali,Grocery,Tea,South India Distribution,251.42,283.32,31.90,1335
442,P00443,Patanjali Cooking Oil,Patanjali,Grocery,Cooking Oil,NextGen Distributors,131.14,172.54,41.40,1318
315,P00316,Tata Sugar,Tata,Grocery,Sugar,Sunrise Enterprises,946.34,1192.33,245.99,1318
18,P00019,Patanjali Cooking Oil,Patanjali,Grocery,Cooking Oil,ABC Traders,1376.55,1561.51,184.96,1299
234,P00235,Tata Sugar,Tata,Grocery,Sugar,Retail Connect,1356.73,1829.81,473.08,1278
317,P00318,Aashirvaad Cooking Oil,Aashirvaad,Grocery,Cooking Oil,Metro Suppliers,1553.79,2037.75,483.96,1201
106,P00107,Patanjali Rice,Patanjali,Grocery,Rice,Global Imports,216.95,285.51,68.56,1200
453,P00454,Tata Coffee,Tata,Grocery,Coffee,Quick Supply Chain,1875.86,2271.14,395.28,1199

In [43]:
products_df = products_df.sort_values(
    by="product_id"
)

In [44]:
products_df.reset_index(
    drop=True,
    inplace=True
)

In [45]:
import os

os.makedirs(
    "Data/Generated",
    exist_ok=True
)

In [46]:
products_df.to_csv(
    "Data/Generated/products.csv",
    index=False
)

In [47]:
from google.colab import files

files.download(
    "Data/Generated/products.csv"
)