<a href="https://colab.research.google.com/github/Pranayshukla0610/Data-Science-Projects/blob/main/Notebooks_5_order_details.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random
import pandas as pd
import numpy as np

In [2]:
random.seed(42)
np.random.seed(42)

In [3]:
orders_df = pd.read_csv('/content/orders (2).csv')

In [4]:
products_df = pd.read_csv('/content/products (1).csv')

In [5]:
print("Orders :", orders_df.shape)
print("Products :", products_df.shape)

Orders : (100000, 14)
Products : (500, 10)

In [6]:
product_price_lookup = dict(
    zip(
        products_df["product_id"],
        products_df["selling_price"]
    )
)

product_profit_lookup = dict(
    zip(
        products_df["product_id"],
        products_df["profit_margin"]
    )
)

In [7]:
product_ids = products_df['product_id'].tolist()

In [8]:
order_ids = orders_df['order_id'].tolist()

In [9]:
MIN_PRODUCTS_PER_ORDER = 1
MAX_PRODUCTS_PER_ORDER = 5

In [10]:
discount_options = [
    0,
    5,
    10,
    15,
    20,
    25,
    30
]

In [11]:
discount_probability = [
    0.30,
    0.20,
    0.20,
    0.10,
    0.10,
    0.05,
    0.05
]

In [12]:
quantity_options = [
    1,
    2,
    3,
    4,
    5
]

In [13]:
quantity_probability = [
    0.45,
    0.25,
    0.15,
    0.10,
    0.05
]

In [14]:
order_detail_id_list = []

order_id_list = []

product_id_list = []

quantity_list = []

unit_price_list = []

discount_list = []

line_sales_list = []

line_profit_list = []

In [15]:
detail_counter = 1

In [16]:
print("=" * 60)

print("ORDER DETAILS CONFIGURATION")

print("=" * 60)

print("Orders :", len(order_ids))

print("Products :", len(product_ids))

print("Products per Order :",
      f"{MIN_PRODUCTS_PER_ORDER}-{MAX_PRODUCTS_PER_ORDER}")

print("=" * 60)

============================================================
ORDER DETAILS CONFIGURATION
============================================================
Orders : 100000
Products : 500
Products per Order : 1-5
============================================================

In [17]:
estimated_rows = len(order_ids) * 3

print("Estimated Order Detail Records:", estimated_rows)

Estimated Order Detail Records: 300000

In [18]:
for order_id in order_ids:

    # Number of products in this order
    number_of_products = random.randint(
        MIN_PRODUCTS_PER_ORDER,
        MAX_PRODUCTS_PER_ORDER
    )

    # Ensure unique products in an order
    selected_products = random.sample(
        product_ids,
        number_of_products
    )

    for product in selected_products:

        # Quantity
        quantity = np.random.choice(
            quantity_options,
            p=quantity_probability
        )

        # Unit Price
        unit_price = product_price_lookup[product]

        # Discount
        discount = np.random.choice(
            discount_options,
            p=discount_probability
        )

        # Gross Sales
        gross_sales = quantity * unit_price

        # Discount Amount
        discount_amount = gross_sales * (discount / 100)

        # Final Sales
        line_sales = round(
            gross_sales - discount_amount,
            2
        )

        # Profit Margin
        profit_margin = product_profit_lookup[product]

        # Line Profit
        line_profit = round(
            (profit_margin * quantity) - discount_amount,
            2
        )

        # Order Detail ID
        order_detail_id = f"OD{detail_counter:08d}"

        detail_counter += 1

        # Store Values
        order_detail_id_list.append(order_detail_id)

        order_id_list.append(order_id)

        product_id_list.append(product)

        quantity_list.append(quantity)

        unit_price_list.append(unit_price)

        discount_list.append(discount)

        line_sales_list.append(line_sales)

        line_profit_list.append(line_profit)

In [19]:
order_details_df = pd.DataFrame({

    "order_detail_id": order_detail_id_list,

    "order_id": order_id_list,

    "product_id": product_id_list,

    "quantity": quantity_list,

    "unit_price": unit_price_list,

    "discount_percent": discount_list,

    "line_sales": line_sales_list,

    "line_profit": line_profit_list

})

In [20]:
order_details_df.groupby("order_id").size().describe()

count    100000.000000
mean          3.007720
std           1.415606
min           1.000000
25%           2.000000
50%           3.000000
75%           4.000000
max           5.000000
dtype: float64

In [21]:
order_details_df.sort_values(
    by="line_sales",
    ascending=False
).head(10)

,order_detail_id,order_id,product_id,quantity,unit_price,discount_percent,line_sales,line_profit
279364,OD00279365,O0092891,P00251,5,144949.30,0,724746.50,159714.30
112866,OD00112867,O0037464,P00251,5,144949.30,0,724746.50,159714.30
58490,OD00058491,O0019419,P00251,5,144949.30,0,724746.50,159714.30
255577,OD00255578,O0085013,P00251,5,144949.30,0,724746.50,159714.30
214482,OD00214483,O0071369,P00251,5,144949.30,0,724746.50,159714.30
256208,OD00256209,O0085227,P00251,5,144949.30,0,724746.50,159714.30
253514,OD00253515,O0084335,P00251,5,144949.30,0,724746.50,159714.30
102896,OD00102897,O0034134,P00251,5,144949.30,0,724746.50,159714.30
87700,OD00087701,O0029104,P00251,5,144949.30,0,724746.50,159714.30
160319,OD00160320,O0053283,P00432,5,138521.05,0,692605.25,112544.15

In [22]:
order_details_df.sort_values(
    by="line_profit",
    ascending=False
).head(10)

,order_detail_id,order_id,product_id,quantity,unit_price,discount_percent,line_sales,line_profit
214482,OD00214483,O0071369,P00251,5,144949.30,0,724746.50,159714.3
253514,OD00253515,O0084335,P00251,5,144949.30,0,724746.50,159714.3
112866,OD00112867,O0037464,P00251,5,144949.30,0,724746.50,159714.3
255577,OD00255578,O0085013,P00251,5,144949.30,0,724746.50,159714.3
58490,OD00058491,O0019419,P00251,5,144949.30,0,724746.50,159714.3
279364,OD00279365,O0092891,P00251,5,144949.30,0,724746.50,159714.3
256208,OD00256209,O0085227,P00251,5,144949.30,0,724746.50,159714.3
102896,OD00102897,O0034134,P00251,5,144949.30,0,724746.50,159714.3
87700,OD00087701,O0029104,P00251,5,144949.30,0,724746.50,159714.3
51871,OD00051872,O0017209,P00334,5,119259.93,0,596299.65,150378.2

In [23]:
sample_order = random.choice(order_ids)

order_details_df[
    order_details_df["order_id"] == sample_order
]

,order_detail_id,order_id,product_id,quantity,unit_price,discount_percent,line_sales,line_profit
2306,OD00002307,O0000775,P00449,2,4939.52,0,9879.04,2749.86
2307,OD00002308,O0000775,P00020,1,10346.48,5,9829.16,812.21
2308,OD00002309,O0000775,P00005,3,1959.70,20,4703.28,465.06

In [24]:
order_details_df.isnull().sum()

order_detail_id     0
order_id            0
product_id          0
quantity            0
unit_price          0
discount_percent    0
line_sales          0
line_profit         0
dtype: int64

In [25]:
order_details_df["order_detail_id"].duplicated().sum()

np.int64(0)

In [26]:
invalid_orders = order_details_df[
    ~order_details_df["order_id"].isin(order_ids)
]

print("Invalid Order IDs :", len(invalid_orders))

Invalid Order IDs : 0

In [27]:
invalid_products = order_details_df[
    ~order_details_df["product_id"].isin(product_ids)
]

print("Invalid Product IDs :", len(invalid_products))

Invalid Product IDs : 0

In [28]:
duplicate_products = order_details_df.duplicated(
    subset=["order_id", "product_id"]
).sum()

print("Duplicate Products Within Same Order :", duplicate_products)

Duplicate Products Within Same Order : 0

In [29]:
print(
    "Invalid Quantities :",
    (order_details_df["quantity"] <= 0).sum()
)

Invalid Quantities : 0

In [30]:
print(
    "Invalid Unit Prices :",
    (order_details_df["unit_price"] <= 0).sum()
)

Invalid Unit Prices : 0

In [31]:
print(
    "Invalid Unit Prices :",
    (order_details_df["unit_price"] <= 0).sum()
)

Invalid Unit Prices : 0

In [32]:
print(
    "Negative Profit :",
    (order_details_df["line_profit"] < 0).sum()
)

Negative Profit : 51738

In [33]:
order_items = (
    order_details_df.groupby("order_id")
    .size()
)

order_items.describe()

count    100000.000000
mean          3.007720
std           1.415606
min           1.000000
25%           2.000000
50%           3.000000
75%           4.000000
max           5.000000
dtype: float64

In [34]:
order_items = (
    order_details_df.groupby("order_id")
    .size()
)

order_items.describe()

count    100000.000000
mean          3.007720
std           1.415606
min           1.000000
25%           2.000000
50%           3.000000
75%           4.000000
max           5.000000
dtype: float64

In [35]:
order_details_df.sort_values(
    by="line_profit",
    ascending=False
).head(10)

,order_detail_id,order_id,product_id,quantity,unit_price,discount_percent,line_sales,line_profit
214482,OD00214483,O0071369,P00251,5,144949.30,0,724746.50,159714.3
253514,OD00253515,O0084335,P00251,5,144949.30,0,724746.50,159714.3
112866,OD00112867,O0037464,P00251,5,144949.30,0,724746.50,159714.3
255577,OD00255578,O0085013,P00251,5,144949.30,0,724746.50,159714.3
58490,OD00058491,O0019419,P00251,5,144949.30,0,724746.50,159714.3
279364,OD00279365,O0092891,P00251,5,144949.30,0,724746.50,159714.3
256208,OD00256209,O0085227,P00251,5,144949.30,0,724746.50,159714.3
102896,OD00102897,O0034134,P00251,5,144949.30,0,724746.50,159714.3
87700,OD00087701,O0029104,P00251,5,144949.30,0,724746.50,159714.3
51871,OD00051872,O0017209,P00334,5,119259.93,0,596299.65,150378.2

In [36]:
sample_order = random.choice(order_ids)

order_details_df[
    order_details_df["order_id"] == sample_order
]

,order_detail_id,order_id,product_id,quantity,unit_price,discount_percent,line_sales,line_profit
219000,OD00219001,O0072863,P00202,2,24290.89,0,48581.78,11519.36

In [37]:
order_details_df = order_details_df.sort_values(
    by="order_detail_id"
)

In [38]:
order_details_df = order_details_df.sort_values(
    by="order_detail_id"
)

In [40]:
import os

os.makedirs(
    "Data/Generated",
    exist_ok=True
)

In [41]:
order_details_df.to_csv(
    "Data/Generated/order_details.csv",
    index=False
)

In [42]:
from google.colab import files

files.download(
    "Data/Generated/order_details.csv"
)