<a href="https://colab.research.google.com/github/Pranayshukla0610/Data-Science-Projects/blob/main/Notebook_6_Inventory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random
import pandas as pd
import numpy as np

from datetime import timedelta
from datetime import datetime

In [2]:
random.seed(42)
np.random.seed(42)

In [3]:
products_df = pd.read_csv('/content/products (1).csv')

In [4]:
regions_df = pd.read_csv('/content/regions.csv')

In [5]:
print("Products :", products_df.shape)
print("Regions :", regions_df.shape)

Products : (500, 10)
Regions : (20, 7)

In [6]:
product_ids = products_df["product_id"].tolist()

In [7]:
region_ids = regions_df["region_id"].tolist()

In [8]:
product_price_lookup = dict(
    zip(
        products_df["product_id"],
        products_df["selling_price"]
    )
)

In [9]:
warehouse_names = [
    'North Warehouse',
    'South Warehouse',
    'East Warehouse',
    'West Warehouse',
    'Central Warehouse'
]

In [11]:
warehouse_lookup = {}

for _,row in regions_df.iterrows():
  zone = row['zone']

  if zone == 'North':
    warehouse = 'North Warehouse'
  elif zone == 'South':
    warehouse = 'South Warehouse'
  elif zone == 'West':
    warehouse = 'West Warehouse'
  elif zone == 'East':
    warehouse = 'East Warehouse'
  else:
    warehouse = 'Central Warehouse'

  warehouse_lookup[row["region_id"]] = warehouse

In [12]:
start_date = datetime(2023, 1, 1)
end_date = datetime(2026, 12, 31)

date_difference = (
    end_date - start_date
).days

In [13]:
NUMBER_OF_PRODUCTS = len(product_ids)

NUMBER_OF_REGIONS = len(region_ids)

print("Products :", NUMBER_OF_PRODUCTS)

print("Regions :", NUMBER_OF_REGIONS)

Products : 500
Regions : 20

In [14]:
inventory_id_list = []

product_id_list = []

region_id_list = []

warehouse_list = []

opening_stock_list = []

stock_received_list = []

stock_sold_list = []

current_stock_list = []

reorder_level_list = []

stock_status_list = []

inventory_value_list = []

last_restock_date_list = []

In [15]:
stock_status_options = [

    "Low Stock",

    "In Stock",

    "Overstock"

]

In [16]:
print("=" * 60)

print("INVENTORY CONFIGURATION")

print("=" * 60)

print("Products :", len(product_ids))

print("Regions :", len(region_ids))

print("Expected Inventory Records :",
      len(product_ids) * len(region_ids))

print("=" * 60)

============================================================
INVENTORY CONFIGURATION
============================================================
Products : 500
Regions : 20
Expected Inventory Records : 10000
============================================================

In [18]:
inventory_counter = 1

In [19]:
for region in region_ids:

    warehouse = warehouse_lookup[region]

    for product in product_ids:

        # Inventory ID
        inventory_id = f"INV{inventory_counter:06d}"

        inventory_counter += 1

        # Opening Stock
        opening_stock = random.randint(100, 1000)

        # Stock Received
        stock_received = random.randint(50, 500)

        # Stock Sold
        max_stock_available = opening_stock + stock_received

        stock_sold = random.randint(
            0,
            max_stock_available
        )

        # Current Stock
        current_stock = (
            opening_stock
            + stock_received
            - stock_sold
        )

        # Reorder Level
        reorder_level = random.randint(80, 250)

        # Stock Status
        if current_stock <= reorder_level:

            stock_status = "Low Stock"

        elif current_stock >= reorder_level * 3:

            stock_status = "Overstock"

        else:

            stock_status = "In Stock"

        # Selling Price
        selling_price = product_price_lookup[product]

        # Inventory Value
        inventory_value = round(
            current_stock * selling_price,
            2
        )

        # Last Restock Date
        last_restock_date = (
            start_date
            + timedelta(
                days=random.randint(
                    0,
                    date_difference
                )
            )
        )

        # Store Values

        inventory_id_list.append(inventory_id)

        product_id_list.append(product)

        region_id_list.append(region)

        warehouse_list.append(warehouse)

        opening_stock_list.append(opening_stock)

        stock_received_list.append(stock_received)

        stock_sold_list.append(stock_sold)

        current_stock_list.append(current_stock)

        reorder_level_list.append(reorder_level)

        stock_status_list.append(stock_status)

        inventory_value_list.append(inventory_value)

        last_restock_date_list.append(last_restock_date)

In [20]:
inventory_df = pd.DataFrame({

    "inventory_id": inventory_id_list,

    "product_id": product_id_list,

    "region_id": region_id_list,

    "warehouse_name": warehouse_list,

    "opening_stock": opening_stock_list,

    "stock_received": stock_received_list,

    "stock_sold": stock_sold_list,

    "current_stock": current_stock_list,

    "reorder_level": reorder_level_list,

    "stock_status": stock_status_list,

    "inventory_value": inventory_value_list,

    "last_restock_date": last_restock_date_list

})

In [21]:
inventory_df['stock_status'].value_counts()

stock_status
In Stock     3987
Overstock    3700
Low Stock    2313
Name: count, dtype: int64

In [22]:
inventory_df.sort_values(
    by = 'inventory_value',
    ascending = False
).head(10)

,inventory_id,product_id,region_id,warehouse_name,opening_stock,stock_received,stock_sold,current_stock,reorder_level,stock_status,inventory_value,last_restock_date
9307,INV009308,P00308,R019,North Warehouse,924,456,123,1257,126,Overstock,1.582018e+08,2026-10-30
7981,INV007982,P00482,R016,South Warehouse,765,428,36,1157,105,Overstock,1.552775e+08,2024-12-29
6273,INV006274,P00274,R013,North Warehouse,986,489,134,1341,196,Overstock,1.492760e+08,2023-11-23
3807,INV003808,P00308,R008,Central Warehouse,852,371,72,1151,104,Overstock,1.448610e+08,2023-05-14
1431,INV001432,P00432,R003,South Warehouse,779,319,89,1009,145,Overstock,1.397677e+08,2023-12-15
1931,INV001932,P00432,R004,West Warehouse,787,386,184,989,181,Overstock,1.369973e+08,2023-10-15
1981,INV001982,P00482,R004,West Warehouse,720,393,93,1020,81,Overstock,1.368912e+08,2024-06-03
250,INV000251,P00251,R001,Central Warehouse,779,455,311,923,206,Overstock,1.337882e+08,2023-03-17
260,INV000261,P00261,R001,Central Warehouse,878,374,205,1047,193,Overstock,1.333852e+08,2023-12-07
2273,INV002274,P00274,R005,East Warehouse,909,348,74,1183,133,Overstock,1.316879e+08,2024-03-25

In [23]:
inventory_df.sort_values(
    by='current_stock'
).head(10)

,inventory_id,product_id,region_id,warehouse_name,opening_stock,stock_received,stock_sold,current_stock,reorder_level,stock_status,inventory_value,last_restock_date
1470,INV001471,P00471,R003,South Warehouse,537,257,794,0,90,Low Stock,0.0,2026-05-30
4975,INV004976,P00476,R010,East Warehouse,230,113,343,0,222,Low Stock,0.0,2026-11-23
7092,INV007093,P00093,R015,North Warehouse,345,176,521,0,121,Low Stock,0.0,2024-08-01
9031,INV009032,P00032,R019,North Warehouse,497,353,850,0,174,Low Stock,0.0,2023-05-31
3823,INV003824,P00324,R008,Central Warehouse,680,226,906,0,166,Low Stock,0.0,2023-06-24
2140,INV002141,P00141,R005,East Warehouse,252,493,745,0,163,Low Stock,0.0,2023-07-02
5864,INV005865,P00365,R012,East Warehouse,778,359,1137,0,245,Low Stock,0.0,2025-01-26
3705,INV003706,P00206,R008,Central Warehouse,120,500,620,0,95,Low Stock,0.0,2026-02-14
7382,INV007383,P00383,R015,North Warehouse,321,243,564,0,223,Low Stock,0.0,2024-04-18
8459,INV008460,P00460,R017,West Warehouse,342,385,727,0,241,Low Stock,0.0,2023-02-24

In [24]:
inventory_df.sort_values(
    by="current_stock",
    ascending=False
).head(10)

,inventory_id,product_id,region_id,warehouse_name,opening_stock,stock_received,stock_sold,current_stock,reorder_level,stock_status,inventory_value,last_restock_date
9729,INV009730,P00230,R020,North Warehouse,982,487,22,1447,133,Overstock,982628.76,2026-09-23
6349,INV006350,P00350,R013,North Warehouse,969,483,13,1439,159,Overstock,11857072.20,2024-05-22
6079,INV006080,P00080,R013,North Warehouse,966,495,44,1417,123,Overstock,2310815.26,2023-04-02
9264,INV009265,P00265,R019,North Warehouse,983,477,44,1416,189,Overstock,4523058.00,2023-06-28
3914,INV003915,P00415,R008,Central Warehouse,938,486,22,1402,156,Overstock,32474890.52,2024-06-18
5933,INV005934,P00434,R012,East Warehouse,986,446,37,1395,168,Overstock,298725.30,2023-07-21
489,INV000490,P00490,R001,Central Warehouse,945,492,58,1379,100,Overstock,4128822.53,2023-04-04
4511,INV004512,P00012,R010,East Warehouse,937,496,55,1378,178,Overstock,3366881.18,2023-11-12
2245,INV002246,P00246,R005,East Warehouse,997,454,86,1365,206,Overstock,685953.45,2024-03-25
4564,INV004565,P00065,R010,East Warehouse,943,471,52,1362,92,Overstock,4276257.78,2023-05-16

In [25]:
inventory_df.sample(10)

,inventory_id,product_id,region_id,warehouse_name,opening_stock,stock_received,stock_sold,current_stock,reorder_level,stock_status,inventory_value,last_restock_date
6252,INV006253,P00253,R013,North Warehouse,889,171,669,391,157,In Stock,13982543.18,2026-11-08
4684,INV004685,P00185,R010,East Warehouse,719,425,269,875,202,Overstock,2244856.25,2023-01-14
1731,INV001732,P00232,R004,West Warehouse,435,272,593,114,136,Low Stock,482453.70,2026-04-26
4742,INV004743,P00243,R010,East Warehouse,120,342,170,292,146,In Stock,661377.08,2024-06-03
4521,INV004522,P00022,R010,East Warehouse,588,491,279,800,184,Overstock,992448.00,2023-04-05
6340,INV006341,P00341,R013,North Warehouse,683,298,436,545,189,In Stock,3901393.40,2026-05-31
576,INV000577,P00077,R002,West Warehouse,818,331,964,185,217,Low Stock,698317.65,2026-09-22
5202,INV005203,P00203,R011,South Warehouse,266,50,27,289,125,In Stock,925866.41,2026-02-02
6363,INV006364,P00364,R013,North Warehouse,541,63,454,150,216,Low Stock,559614.00,2025-05-01
439,INV000440,P00440,R001,Central Warehouse,590,373,186,777,114,Overstock,577140.06,2023-05-10

In [26]:
inventory_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   inventory_id       10000 non-null  object
 1   product_id         10000 non-null  object
 2   region_id          10000 non-null  object
 3   warehouse_name     10000 non-null  object
 4   opening_stock      10000 non-null  int64
 5   stock_received     10000 non-null  int64
 6   stock_sold         10000 non-null  int64
 7   current_stock      10000 non-null  int64
 8   reorder_level      10000 non-null  int64
 9   stock_status       10000 non-null  object
 10  inventory_value    10000 non-null  float64
 11  last_restock_date  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(5), object(5)
memory usage: 937.6+ KB

In [27]:
invalid_products = inventory_df[
    ~inventory_df["product_id"].isin(product_ids)
]

print("Invalid Product IDs :", len(invalid_products))

Invalid Product IDs : 0

In [28]:
inventory_df.head()

,inventory_id,product_id,region_id,warehouse_name,opening_stock,stock_received,stock_sold,current_stock,reorder_level,stock_status,inventory_value,last_restock_date
0,INV000001,P00001,R001,Central Warehouse,754,107,25,836,150,Overstock,6920015.08,2024-05-16
1,INV000002,P00002,R001,Central Warehouse,328,121,377,72,106,Low Stock,856041.12,2026-10-17
2,INV000003,P00003,R001,Central Warehouse,858,329,178,1009,231,Overstock,19009388.47,2025-05-14
3,INV000004,P00004,R001,Central Warehouse,132,65,23,174,135,In Stock,3111299.22,2024-04-21
4,INV000005,P00005,R001,Central Warehouse,617,358,27,948,223,Overstock,1857795.60,2024-02-12

In [30]:
invalid_stock = inventory_df[
    inventory_df["current_stock"] != (
        inventory_df["opening_stock"]
        + inventory_df["stock_received"]
        - inventory_df["stock_sold"]
    )
]

print("Invalid Stock Calculations :", len(invalid_stock))

Invalid Stock Calculations : 0

In [31]:
print(
    "Negative Current Stock :",
    (inventory_df["current_stock"] < 0).sum()
)

Negative Current Stock : 0

In [32]:
invalid_value = inventory_df[
    inventory_df["inventory_value"] <= 0
]

print("Invalid Inventory Value :", len(invalid_value))

Invalid Inventory Value : 14

In [33]:
inventory_df.sort_values(
    by="inventory_value",
    ascending=False
).head(10)

,inventory_id,product_id,region_id,warehouse_name,opening_stock,stock_received,stock_sold,current_stock,reorder_level,stock_status,inventory_value,last_restock_date
9307,INV009308,P00308,R019,North Warehouse,924,456,123,1257,126,Overstock,1.582018e+08,2026-10-30
7981,INV007982,P00482,R016,South Warehouse,765,428,36,1157,105,Overstock,1.552775e+08,2024-12-29
6273,INV006274,P00274,R013,North Warehouse,986,489,134,1341,196,Overstock,1.492760e+08,2023-11-23
3807,INV003808,P00308,R008,Central Warehouse,852,371,72,1151,104,Overstock,1.448610e+08,2023-05-14
1431,INV001432,P00432,R003,South Warehouse,779,319,89,1009,145,Overstock,1.397677e+08,2023-12-15
1931,INV001932,P00432,R004,West Warehouse,787,386,184,989,181,Overstock,1.369973e+08,2023-10-15
1981,INV001982,P00482,R004,West Warehouse,720,393,93,1020,81,Overstock,1.368912e+08,2024-06-03
250,INV000251,P00251,R001,Central Warehouse,779,455,311,923,206,Overstock,1.337882e+08,2023-03-17
260,INV000261,P00261,R001,Central Warehouse,878,374,205,1047,193,Overstock,1.333852e+08,2023-12-07
2273,INV002274,P00274,R005,East Warehouse,909,348,74,1183,133,Overstock,1.316879e+08,2024-03-25

In [34]:
inventory_df.sort_values(
    by="inventory_value",
    ascending=False
).head(10)

,inventory_id,product_id,region_id,warehouse_name,opening_stock,stock_received,stock_sold,current_stock,reorder_level,stock_status,inventory_value,last_restock_date
9307,INV009308,P00308,R019,North Warehouse,924,456,123,1257,126,Overstock,1.582018e+08,2026-10-30
7981,INV007982,P00482,R016,South Warehouse,765,428,36,1157,105,Overstock,1.552775e+08,2024-12-29
6273,INV006274,P00274,R013,North Warehouse,986,489,134,1341,196,Overstock,1.492760e+08,2023-11-23
3807,INV003808,P00308,R008,Central Warehouse,852,371,72,1151,104,Overstock,1.448610e+08,2023-05-14
1431,INV001432,P00432,R003,South Warehouse,779,319,89,1009,145,Overstock,1.397677e+08,2023-12-15
1931,INV001932,P00432,R004,West Warehouse,787,386,184,989,181,Overstock,1.369973e+08,2023-10-15
1981,INV001982,P00482,R004,West Warehouse,720,393,93,1020,81,Overstock,1.368912e+08,2024-06-03
250,INV000251,P00251,R001,Central Warehouse,779,455,311,923,206,Overstock,1.337882e+08,2023-03-17
260,INV000261,P00261,R001,Central Warehouse,878,374,205,1047,193,Overstock,1.333852e+08,2023-12-07
2273,INV002274,P00274,R005,East Warehouse,909,348,74,1183,133,Overstock,1.316879e+08,2024-03-25

In [35]:
import os

os.makedirs(
    "Data/Generated",
    exist_ok=True
)

In [36]:
inventory_df.to_csv(
    "Data/Generated/inventory.csv",
    index=False
)

In [37]:
from google.colab import files

files.download(
    "Data/Generated/inventory.csv"
)