<a href="https://colab.research.google.com/github/Pranayshukla0610/Data-Science-Projects/blob/main/Notebook_4_Orders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
!pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.12/dist-packages (40.23.0)

In [40]:
import random
import pandas as pd
import numpy as np
from datetime import datetime
from datetime import timedelta

In [41]:
random.seed(42)
np.random.seed(42)

In [42]:
NUMBER_OF_ORDERS = 100000

In [43]:
customer_df = pd.read_csv('/content/customers (1).csv')

In [44]:
products_df = pd.read_csv('/content/products (1).csv')

In [45]:
regions_df = pd.read_csv('/content/regions.csv')

In [46]:
print(customer_df.shape)
print(products_df.shape)
print(regions_df.shape)

(15000, 7)
(500, 10)
(20, 7)

In [47]:
customer_ids = customer_df['customer_id'].tolist()

In [48]:
product_ids = products_df['product_id'].tolist()

In [49]:
region_ids = regions_df['region_id'].tolist()

In [50]:
print(len(customer_ids))
print(len(product_ids))
print(region_ids)

15000
500
['R001', 'R002', 'R003', 'R004', 'R005', 'R006', 'R007', 'R008', 'R009', 'R010', 'R011', 'R012', 'R013', 'R014', 'R015', 'R016', 'R017', 'R018', 'R019', 'R020']

In [51]:
order_ids = [
    f"O{str(i).zfill(7)}"
    for i in range(
        1,
        NUMBER_OF_ORDERS+1
    )
]

In [52]:
order_ids[:10]

['O0000001',
 'O0000002',
 'O0000003',
 'O0000004',
 'O0000005',
 'O0000006',
 'O0000007',
 'O0000008',
 'O0000009',
 'O0000010']

In [53]:
payment_methods = [
    'UPI',
    'Credit Card',
    'Debit Card',
    'Net Banking',
    'Cash on Delivery',
    'Wallet'
]

In [54]:
payment_probability = [
    0.40,
    0.20,
    0.15,
    0.05,
    0.15,
    0.05
]

In [55]:
order_status = [
    'Delivered',
    'Shipped',
    'Cancelled',
    'Returned'
]

In [56]:
status_probability = [
    0.88,
    0.07,
    0.03,
    0.02
]

In [57]:
discount_options = [
    0,
    5,
    10,
    15,
    20,
    25,
    30
]

In [58]:
discount_probability = [

    0.30,

    0.20,

    0.20,

    0.10,

    0.10,

    0.05,

    0.05

]

In [59]:
quantity_options = [
    1,
    2,
    3,
    4,
    5
]

In [60]:
quantity_probability = [
    0.45,
    0.25,
    0.15,
    0.10,
    0.05
]

In [61]:
start_date = datetime(2023,1,1)
end_date = datetime(2026,12,31)

In [62]:
date_difference = (
    end_date - start_date
).days

In [63]:
print("="*60)

print("ORDER DATA CONFIGURATION")

print("="*60)

print("Orders :",NUMBER_OF_ORDERS)

print("Customers :",len(customer_ids))

print("Products :",len(product_ids))

print("Regions :",len(region_ids))

print("Payment Methods :",payment_methods)

print("Order Status :",order_status)

print("="*60)

============================================================
ORDER DATA CONFIGURATION
============================================================
Orders : 100000
Customers : 15000
Products : 500
Regions : 20
Payment Methods : ['UPI', 'Credit Card', 'Debit Card', 'Net Banking', 'Cash on Delivery', 'Wallet']
Order Status : ['Delivered', 'Shipped', 'Cancelled', 'Returned']
============================================================

In [64]:
product_price_lookup = dict(
    zip(
        products_df["product_id"],
        products_df["selling_price"]
    )
)

In [65]:
list(product_price_lookup.items())[:5]

[('P00001', 8277.53),
 ('P00002', 11889.46),
 ('P00003', 18839.83),
 ('P00004', 17881.03),
 ('P00005', 1959.7)]

In [66]:
product_profit_lookup = dict(
    zip(
        products_df["product_id"],
        products_df["profit_margin"]
    )
)

In [67]:
print("Everything Loaded Successfully!")

print()

print("Ready to Generate 100,000 Orders")

Everything Loaded Successfully!

Ready to Generate 100,000 Orders

In [68]:
order_date_list = []
ship_date_list = []

customer_id_list = []
product_id_list = []
region_id_list = []

quantity_list = []

payment_method_list = []
order_status_list = []

discount_list = []

unit_price_list = []

sales_amount_list = []

profit_list = []

shipping_cost_list = []

In [69]:
customer_region_lookup = {}

for customer in customer_ids:
    customer_region_lookup[customer] = random.choice(region_ids)

In [70]:
for order_id in order_ids:

    # -------------------------
    # Customer
    # -------------------------
    customer = random.choice(customer_ids)

    # Region (fixed for customer)
    region = customer_region_lookup[customer]

    # Product
    product = random.choice(product_ids)

    # Quantity
    quantity = np.random.choice(
        quantity_options,
        p=quantity_probability
    )

    # Unit Price
    unit_price = product_price_lookup[product]

    # Discount
    discount = np.random.choice(
        discount_options,
        p=discount_probability
    )

    # Gross Sales
    gross_sales = unit_price * quantity

    # Discount Amount
    discount_amount = gross_sales * (discount / 100)

    # Final Sales
    sales_amount = round(
        gross_sales - discount_amount,
        2
    )

    # Profit
    unit_profit = product_profit_lookup[product]

    profit = round(
        (unit_profit * quantity) - discount_amount,
        2
    )

    # Shipping Cost
    shipping_cost = round(
        random.uniform(50, 500),
        2
    )

    # Payment Method
    payment = np.random.choice(
        payment_methods,
        p=payment_probability
    )

    # Order Status
    status = np.random.choice(
        order_status,
        p=status_probability
    )

    # Random Order Date
    order_date = start_date + timedelta(
        days=random.randint(
            0,
            date_difference
        )
    )

    # Shipping Date
    ship_date = order_date + timedelta(
        days=random.randint(1, 7)
    )

    # Store Values
    customer_id_list.append(customer)

    product_id_list.append(product)

    region_id_list.append(region)

    quantity_list.append(quantity)

    payment_method_list.append(payment)

    order_status_list.append(status)

    discount_list.append(discount)

    unit_price_list.append(unit_price)

    sales_amount_list.append(sales_amount)

    profit_list.append(profit)

    shipping_cost_list.append(shipping_cost)

    order_date_list.append(order_date)

    ship_date_list.append(ship_date)

In [71]:
print("order_ids               :", len(order_ids))
print("customer_id_list        :", len(customer_id_list))
print("product_id_list         :", len(product_id_list))
print("region_id_list          :", len(region_id_list))
print("order_date_list         :", len(order_date_list))
print("ship_date_list          :", len(ship_date_list))
print("quantity_list           :", len(quantity_list))
print("payment_method_list     :", len(payment_method_list))
print("order_status_list       :", len(order_status_list))
print("discount_list           :", len(discount_list))
print("unit_price_list         :", len(unit_price_list))
print("sales_amount_list       :", len(sales_amount_list))
print("profit_list             :", len(profit_list))
print("shipping_cost_list      :", len(shipping_cost_list))

order_ids               : 100000
customer_id_list        : 100000
product_id_list         : 100000
region_id_list          : 100000
order_date_list         : 100000
ship_date_list          : 100000
quantity_list           : 100000
payment_method_list     : 100000
order_status_list       : 100000
discount_list           : 100000
unit_price_list         : 100000
sales_amount_list       : 100000
profit_list             : 100000
shipping_cost_list      : 100000

In [72]:
orders_df = pd.DataFrame({

    "order_id": order_ids,

    "customer_id": customer_id_list,

    "product_id": product_id_list,

    "region_id": region_id_list,

    "order_date": order_date_list,

    "ship_date": ship_date_list,

    "quantity": quantity_list,

    "payment_method": payment_method_list,

    "order_status": order_status_list,

    "discount_percent": discount_list,

    "unit_price": unit_price_list,

    "sales_amount": sales_amount_list,

    "profit": profit_list,

    "shipping_cost": shipping_cost_list

})

In [73]:
orders_df.head()

,order_id,customer_id,product_id,region_id,order_date,ship_date,quantity,payment_method,order_status,discount_percent,unit_price,sales_amount,profit,shipping_cost
0,O0000001,C12841,P00025,R001,2026-12-02,2026-12-08,1,Debit Card,Delivered,30,31367.05,21956.94,-5612.96,196.03
1,O0000002,C04312,P00394,R011,2024-03-04,2024-03-09,1,UPI,Delivered,0,10798.86,10798.86,2295.88,407.14
2,O0000003,C12629,P00443,R002,2024-10-21,2024-10-27,2,UPI,Cancelled,15,172.54,293.32,31.04,296.27
3,O0000004,C06576,P00386,R013,2023-12-19,2023-12-26,3,UPI,Delivered,0,803.93,2411.79,673.92,206.84
4,O0000005,C08190,P00439,R002,2024-12-21,2024-12-26,1,Credit Card,Delivered,10,1274.42,1146.98,126.21,89.99

In [74]:
orders_df.sort_values(
    by="sales_amount",
    ascending=False
).head(10)

,order_id,customer_id,product_id,region_id,order_date,ship_date,quantity,payment_method,order_status,discount_percent,unit_price,sales_amount,profit,shipping_cost
24260,O0024261,C06747,P00251,R011,2023-12-22,2023-12-24,5,Credit Card,Delivered,0,144949.30,724746.50,159714.30,425.56
18928,O0018929,C09288,P00251,R008,2023-03-11,2023-03-14,5,Wallet,Delivered,0,144949.30,724746.50,159714.30,288.32
93455,O0093456,C14719,P00251,R005,2025-06-26,2025-06-29,5,UPI,Delivered,0,144949.30,724746.50,159714.30,58.92
49160,O0049161,C08606,P00432,R014,2024-03-23,2024-03-28,5,Debit Card,Shipped,0,138521.05,692605.25,112544.15,467.00
77520,O0077521,C14954,P00432,R020,2026-10-22,2026-10-28,5,UPI,Delivered,0,138521.05,692605.25,112544.15,114.98
38088,O0038089,C10896,P00432,R015,2023-10-13,2023-10-19,5,Credit Card,Delivered,0,138521.05,692605.25,112544.15,267.28
47593,O0047594,C04104,P00251,R019,2024-10-19,2024-10-20,5,UPI,Delivered,5,144949.30,688509.18,123476.97,213.62
66147,O0066148,C02501,P00251,R002,2026-10-31,2026-11-03,5,Credit Card,Delivered,5,144949.30,688509.18,123476.97,123.06
63412,O0063413,C00404,P00251,R006,2024-02-01,2024-02-07,5,UPI,Delivered,5,144949.30,688509.18,123476.97,379.85
44566,O0044567,C04154,P00482,R003,2023-03-18,2023-03-19,5,Credit Card,Delivered,0,134207.03,671035.15,98279.80,156.06

In [75]:
orders_df.sort_values(
    by="profit",
    ascending=False
).head(10)

,order_id,customer_id,product_id,region_id,order_date,ship_date,quantity,payment_method,order_status,discount_percent,unit_price,sales_amount,profit,shipping_cost
24260,O0024261,C06747,P00251,R011,2023-12-22,2023-12-24,5,Credit Card,Delivered,0,144949.30,724746.50,159714.30,425.56
93455,O0093456,C14719,P00251,R005,2025-06-26,2025-06-29,5,UPI,Delivered,0,144949.30,724746.50,159714.30,58.92
18928,O0018929,C09288,P00251,R008,2023-03-11,2023-03-14,5,Wallet,Delivered,0,144949.30,724746.50,159714.30,288.32
42145,O0042146,C00644,P00334,R008,2024-07-19,2024-07-23,5,UPI,Delivered,0,119259.93,596299.65,150378.20,276.88
2633,O0002634,C10326,P00334,R010,2024-06-02,2024-06-05,5,Credit Card,Delivered,0,119259.93,596299.65,150378.20,132.75
23469,O0023470,C06415,P00334,R004,2024-08-27,2024-09-03,5,Net Banking,Delivered,0,119259.93,596299.65,150378.20,495.40
74701,O0074702,C11991,P00234,R008,2025-10-22,2025-10-26,5,Credit Card,Delivered,0,100317.07,501585.35,138486.25,190.82
58027,O0058028,C09031,P00234,R020,2023-06-14,2023-06-16,5,UPI,Delivered,0,100317.07,501585.35,138486.25,205.04
24476,O0024477,C00537,P00356,R008,2026-06-23,2026-06-30,5,Wallet,Delivered,0,102801.15,514005.75,137916.55,440.19
92539,O0092540,C13981,P00356,R013,2025-10-16,2025-10-18,5,Debit Card,Delivered,0,102801.15,514005.75,137916.55,488.31

In [76]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          100000 non-null  object
 1   customer_id       100000 non-null  object
 2   product_id        100000 non-null  object
 3   region_id         100000 non-null  object
 4   order_date        100000 non-null  datetime64[ns]
 5   ship_date         100000 non-null  datetime64[ns]
 6   quantity          100000 non-null  int64
 7   payment_method    100000 non-null  object
 8   order_status      100000 non-null  object
 9   discount_percent  100000 non-null  int64
 10  unit_price        100000 non-null  float64
 11  sales_amount      100000 non-null  float64
 12  profit            100000 non-null  float64
 13  shipping_cost     100000 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(2), object(6)
memory usage: 10.7+ MB

In [77]:
orders_df["order_id"].duplicated().sum()

np.int64(0)

In [81]:
invalid_customers = orders_df[
    ~orders_df["customer_id"].isin(customer_ids)
]

print("Invalid Customer IDs:", len(invalid_customers))

Invalid Customer IDs: 0

In [82]:
print(
    "Negative Sales :",
    (orders_df["sales_amount"] < 0).sum()
)

Negative Sales : 0

In [83]:
print(
    "Negative Profit :",
    (orders_df["profit"] < 0).sum()
)

Negative Profit : 17194

In [84]:
print(
    "Invalid Shipping Cost :",
    (orders_df["shipping_cost"] <= 0).sum()
)

Invalid Shipping Cost : 0

In [85]:
print(
    "Invalid Shipping Cost :",
    (orders_df["shipping_cost"] <= 0).sum()
)

Invalid Shipping Cost : 0

In [86]:
orders_df.sort_values(
    by="sales_amount",
    ascending=False
).head(10)

,order_id,customer_id,product_id,region_id,order_date,ship_date,quantity,payment_method,order_status,discount_percent,unit_price,sales_amount,profit,shipping_cost
24260,O0024261,C06747,P00251,R011,2023-12-22,2023-12-24,5,Credit Card,Delivered,0,144949.30,724746.50,159714.30,425.56
18928,O0018929,C09288,P00251,R008,2023-03-11,2023-03-14,5,Wallet,Delivered,0,144949.30,724746.50,159714.30,288.32
93455,O0093456,C14719,P00251,R005,2025-06-26,2025-06-29,5,UPI,Delivered,0,144949.30,724746.50,159714.30,58.92
49160,O0049161,C08606,P00432,R014,2024-03-23,2024-03-28,5,Debit Card,Shipped,0,138521.05,692605.25,112544.15,467.00
77520,O0077521,C14954,P00432,R020,2026-10-22,2026-10-28,5,UPI,Delivered,0,138521.05,692605.25,112544.15,114.98
38088,O0038089,C10896,P00432,R015,2023-10-13,2023-10-19,5,Credit Card,Delivered,0,138521.05,692605.25,112544.15,267.28
47593,O0047594,C04104,P00251,R019,2024-10-19,2024-10-20,5,UPI,Delivered,5,144949.30,688509.18,123476.97,213.62
66147,O0066148,C02501,P00251,R002,2026-10-31,2026-11-03,5,Credit Card,Delivered,5,144949.30,688509.18,123476.97,123.06
63412,O0063413,C00404,P00251,R006,2024-02-01,2024-02-07,5,UPI,Delivered,5,144949.30,688509.18,123476.97,379.85
44566,O0044567,C04154,P00482,R003,2023-03-18,2023-03-19,5,Credit Card,Delivered,0,134207.03,671035.15,98279.80,156.06

In [87]:
orders_df.sort_values(
    by="profit",
    ascending=False
).head(10)

,order_id,customer_id,product_id,region_id,order_date,ship_date,quantity,payment_method,order_status,discount_percent,unit_price,sales_amount,profit,shipping_cost
24260,O0024261,C06747,P00251,R011,2023-12-22,2023-12-24,5,Credit Card,Delivered,0,144949.30,724746.50,159714.30,425.56
93455,O0093456,C14719,P00251,R005,2025-06-26,2025-06-29,5,UPI,Delivered,0,144949.30,724746.50,159714.30,58.92
18928,O0018929,C09288,P00251,R008,2023-03-11,2023-03-14,5,Wallet,Delivered,0,144949.30,724746.50,159714.30,288.32
42145,O0042146,C00644,P00334,R008,2024-07-19,2024-07-23,5,UPI,Delivered,0,119259.93,596299.65,150378.20,276.88
2633,O0002634,C10326,P00334,R010,2024-06-02,2024-06-05,5,Credit Card,Delivered,0,119259.93,596299.65,150378.20,132.75
23469,O0023470,C06415,P00334,R004,2024-08-27,2024-09-03,5,Net Banking,Delivered,0,119259.93,596299.65,150378.20,495.40
74701,O0074702,C11991,P00234,R008,2025-10-22,2025-10-26,5,Credit Card,Delivered,0,100317.07,501585.35,138486.25,190.82
58027,O0058028,C09031,P00234,R020,2023-06-14,2023-06-16,5,UPI,Delivered,0,100317.07,501585.35,138486.25,205.04
24476,O0024477,C00537,P00356,R008,2026-06-23,2026-06-30,5,Wallet,Delivered,0,102801.15,514005.75,137916.55,440.19
92539,O0092540,C13981,P00356,R013,2025-10-16,2025-10-18,5,Debit Card,Delivered,0,102801.15,514005.75,137916.55,488.31

In [88]:
import os

os.makedirs(
    "Data/Generated",
    exist_ok=True
)

In [89]:
import os

os.makedirs(
    "Data/Generated",
    exist_ok=True
)

In [91]:
orders_df.to_csv(
    "Data/Generated/orders.csv",
    index=False
)

In [92]:
from google.colab import files

files.download(
    "Data/Generated/orders.csv"
)